nodeLinker: node-modules

enableScripts: true

npmMinimalAgeGate: 0

packageExtensions:
  "@carbon/ibmdotcom-styles@*":
    dependencies:
      react: "^16.14.0"
  "@commitlint/load@*":
    dependencies:
      "@types/node": "*"
      typescript: "*"
  "@typescript-eslint/utils@*":
    dependencies:
      typescript: "*"
  eslint-config-carbon@*:
    dependencies:
      "@babel/core": "*"
      prettier: "*"
      typescript: "*"
  stylelint-config-carbon@*:
    dependencies:
      postcss: "*"
      prettier: "*"

yarnPath: .yarn/releases/yarn-4.15.0.cjs
