name: Deploy demo site to gh-pages

on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # Build directory to deploy
          build_dir: ./packages/demo-site/out
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
